name: example_workflow

on: [push]
  # pull_request:
  #   branches:
  #     - master

jobs:
  code-quality-assurance:
    name: Code quality assurance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint `ls -R|grep .py$|xargs`

  data-quality-assurance:
    name: Data quality assurance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  model-training:
    name: Model training
    needs: [ code-quality-assurance, data-quality-assurance ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2